version: '2'

services:

    spam_classifier:
        restart: always
        build: ./
        volumes:
            - ./:/code
        ports:
            - 8888:8888

        command: jupyter lab --ip=127.0.0.1 --port=8888 --allow-root
